### ISSUE TITLE
matlab-psychtoolbox-3 incorrect dependency

### ISSUE THREAD

**Issue by dev-jam** [neurodebian/Psychtoolbox-3#1]
For some time now there the matlab-psychtoolbox-3 package is not installable (in bookworm, trixie and sid) due to a incorrect dependency. freeglut3 is not available anymore in the repo. libglut3.12 replaced freeglut3. After an update, I always rebuild the package with the correct dependency and then it installs fine. Additionally, the email address team@neuro.debian.net does not seem to work anymore.

**Comment by yarikoptic** [comment]
Thank you for the report!!! (I opened issues on this repo and transferred this issue here)

> Additionally, the email address [team@neuro.debian.net](mailto:team@neuro.debian.net) does not seem to work anymore.

also thanks -- I will see if I can revive that old mail server or redirect elsewhere.

**Comment by dev-jam** [comment]
That was fast!
Thanks!

**Comment by yarikoptic** [comment]
You caught be "red handed" ;)  I will close whenever I upload those non-free packages

**Comment by yarikoptic** [comment]
uploaded -2 where it built, let me know if you don't have it for release you need.  I pushed also changes to the main package but didn't bother uploading since there is transitional freeglut3-dev

**Comment by dev-jam** [comment]
Got the update and it installs correctly.
Thanks!
